### PR TITLE
Close request body

### PR DESCRIPTION
**Pull request by emosbaugh**

### CODE REVIEW

**Comment by salahalsaleh** [comment]
Apparently, the request body will be automatically closed, and there's no need to close it manually. Reference: https://github.com/gin-gonic/gin/issues/1237#issuecomment-394642558

**Comment by emosbaugh** [comment]
But im not sure it will since you are overwriting it.

https://github.com/replicatedhq/kots-lint/pull/54/files#diff-6dcfbfa26b4a45354bac6335aad3c82eb20e0383b180d2fcc80589813d17da2fR59

**Comment by emosbaugh** [comment]
Better link https://github.com/replicatedhq/kots-lint/blob/24cf0b86a1578ec5332e93c8e44c7b247576e33d/pkg/handlers/lint.go#L59

**Comment by salahalsaleh** [comment]
Oh i see, good point.

**Review by salahalsaleh — APPROVED** [review]

**Pull request merged**
